orchestration :
    dependences : "{\"kafka\":[], \"cache\":[\"kafka\"],\"collection\":[\"cache\", \"kafka\"]}"
    serviceDataProperties:
        serviceName : "orchestration"
        ip : "localhost"
        port : 8080
        rootUrl : "/iOrchestration"
    zNodeInfoProperties:
        regZnodePath : "/regManageNode"
        regZnodeChildPath : "/regManageNode/regManageChildNode"
        depZnodePath : "/depManageNode"
        zookeeperHostport : "192.168.56.17:2181"
    kafkaProperties:
        kafkaHostPort : "192.168.56.17:9092,192.168.56.18:9092"
        testTopic: "orchestrationTest"
        kafkaZnodeChildPath : "/regManageNode/kafka"
        
tomcatPort : 8080

endpoints.shutdown.enabled : true