orchestration :
    dependencyProperties : "{\"serviceDependency\":{\"cache\":[\"kafka\",\"redis\"],\"kafka\":[],\"collection\":[\"kafka\",\"cache\"],\"redis\":[]},\"kafkaTopicInfo\":{\"cacheTopic\":10}}"
    serviceDataProperties :
        serviceGroupName : "orchestration"
        serviceName : "orchestration_standalone"
        ip : "172.18.0.21"
        port : 8091
        rootUrl : "/iOrchestration"
    zNodeInfoProperties:
        regZnodePath : "/regManageNode"
        regZnodeChildPath : "/regManageNode/regManageChildNode"
        depZnodePath : "/depManageNode"
        zookeeperHostport : "172.18.0.11:2191"
    monitorProperties:
        kafka:
            serviceGroupName : "kafka"
            serviceName : "kafka"
            kafkaHostPort : "172.18.0.41:9101"
            testTopic: "orchestrationTest"
        redis:
            serviceGroupName : "redis"
            serviceName : "redis"
            redisHost: "172.18.0.71"
            redisPort: "6381"

tomcatPort : 8091

logging.file : "/opt/orchestration/log/console.log"