orchestration :
    dependences : "{\"collection_C\":[],\"collection_B\":[\"collection_C\"],\"collection_A\":[\"collection_C\",\"collection_B\"]}"
    serviceDataProperites:
        serviceName : "orchestration"
        ip : "172.18.0.21"
        port : 8091
        rootUrl : "/iOrchestration"
    zNodeInfoProperites:
        regZnodePath : "/regManageNode"
        regZnodeChildPath : "/regManageNode/regManageChildNode"
        depZnodePath : "/depManageNode"
        zookeeperHostport : "172.18.0.11:2191,172.18.0.12:2192,172.18.0.13:2193"
        
tomcatPort : 8091