orchestration :
    dependences : "{\"kafka\":[], \"ServiceC\":[\"kafka\"],\"ServiceB\":[\"ServiceC\", \"kafka\"],\"ServiceA\":[\"ServiceC\",\"ServiceB\", \"kafka\"]}"
    serviceDataProperties:
        serviceName : "orchestration"
        ip : "172.18.0.22"
        port : 8092
        rootUrl : "/iOrchestration"
    zNodeInfoProperties:
        regZnodePath : "/regManageNode"
        regZnodeChildPath : "/regManageNode/regManageChildNode"
        depZnodePath : "/depManageNode"
        zookeeperHostport : "172.18.0.11:2191,172.18.0.12:2192,172.18.0.13:2193"
    kafkaProperties:
        kafkaHostPort : "192.168.56.17:9092"
        testTopic: "orchestrationTest"
        kafkaZnodeChildPath : "/regManageNode/kafka"
        
tomcatPort : 8092