orchestration :
    dependences : "{\"kafka\":[], \"cache\":[\"kafka\"],\"collection\":[\"cache\", \"kafka\"]}"
    serviceDataProperties:
        serviceGroupName : "orchestration"
        serviceName : "orchestration_1"
        ip : "172.18.0.22"
        port : 8092
        rootUrl : "/iOrchestration"
    zNodeInfoProperties:
        regZnodePath : "/regManageNode"
        regZnodeChildPath : "/regManageNode/regManageChildNode"
        depZnodePath : "/depManageNode"
        zookeeperHostport : "172.18.0.11:2191,172.18.0.12:2192,172.18.0.13:2193"
    kafkaProperties:
        kafkaHostPort : "172.18.0.41:9101,172.18.0.42:9102,172.18.0.43:9103"
        testTopic: "orchestrationTest"
        kafkaZnodeChildPath : "/regManageNode/kafka"

tomcatPort : 8092