orchestration :
    dependences : "{\"ServiceC\":[],\"ServiceB\":[\"ServiceC\"],\"ServiceA\":[\"ServiceC\",\"ServiceB\"]}"
    serviceDataProperites:
        serviceName : "orchestration"
        ip : "172.18.0.21"
        port : 8091
        rootUrl : "/iOrchestration"
    zNodeInfoProperites:
        regZnodePath : "/regManageNode"
        regZnodeChildPath : "/regManageNode/regManageChildNode"
        depZnodePath : "/depManageNode"
        zookeeperHostport : "172.18.0.21:2191,172.18.0.22:2192,172.18.0.23:2193"
        
tomcatPort : 8091