orchestration :
    dependencyProperties : "{\"redisPartitionNum\":10,\"serviceDependency\":{\"cache\":[\"kafka\",\"redis\"],\"kafka\":[],\"aggregation\":[\"kafka\",\"cache\"],\"collection\":[\"kafka\",\"aggregation\",\"cache\"],\"redis\":[]},\"kafkaTopicInfo\":{\"aggregationTopic\":10}}"
    serviceDataProperties :
        serviceGroupName : "orchestration"
        serviceName : "orchestration_standalone"
        ip : "172.18.0.21"
        port : 8091
        rootUrl : "/iOrchestration"
    zNodeInfoProperties:
        regZnodePath : "/regManageNode"
        regZnodeChildPath : "/regManageNode/regManageChildNode"
        depZnodePath : "/depManageNode"
        zookeeperHostport : "172.18.0.11:2191"
    monitorProperties:
        kafka:
            serviceGroupName : "kafka"
            serviceName : "kafka"
            kafkaHostPort : "172.18.0.41:9101"
            testTopic: "orchestrationTest"
        redis:
            redis_1:
                serviceGroupName : "redis"
                serviceName : "redis_1"
                redisHost: "172.18.0.71"
                redisPort: "6381"

tomcatPort : 8091

logging.file : "/opt/orchestration/log/console.log"