orchestration :
    dependences : "{\"ServiceC\":[],\"ServiceB\":[\"ServiceC\"],\"ServiceA\":[\"ServiceC\",\"ServiceB\"]}"
    serviceDataProperites:
        serviceName : "orchestration"
        ip : "localhost"
        port : 8080
        rootUrl : "/iOrchestration"
    zNodeInfoProperites:
        regZnodePath : "/regManageNode"
        regZnodeChildPath : "/regManageNode/regManageChildNode"
        depZnodePath : "/depManageNode"
        zookeeperHostport : "192.168.56.17:2181"
        
tomcatPort : 8080

endpoints.shutdown.enabled : true