orchestration :
    dependencyProperties : "{\"serviceDependency\":{\"cache\":[\"kafka\",\"redis\"],\"kafka\":[],\"collection\":[\"kafka\",\"cache\"],\"redis\":[]},\"kafkaTopicInfo\":{\"cacheTopic\":10}}"
    serviceDataProperties :
        serviceGroupName : "orchestration"
        serviceName : "orchestration_1"
        ip : "localhost"
        port : 8080
        rootUrl : "/iOrchestration"
    zNodeInfoProperties:
        regZnodePath : "/regManageNode"
        regZnodeChildPath : "/regManageNode/regManageChildNode"
        depZnodePath : "/depManageNode"
        zookeeperHostport : "192.168.56.17:2181"
    monitorProperties:
        kafka:
            serviceGroupName : "kafka"
            serviceName : "kafka"
            kafkaHostPort : "192.168.56.17:9092,192.168.56.18:9092"
            testTopic: "orchestrationTest"
        redis:
            serviceGroupName : "redis"
            serviceName : "redis"
            redisHost: "192.168.56.17"
            redisPort: "6379"
        
tomcatPort : 8080

endpoints.shutdown.enabled : true

logging.file : "/Users/yanbinwa/Documents/workspace/springboot/serviceManager/serviceManagerOrchestration/log/orchestrationConsole.log"